### ISSUE TITLE
insufficient_quota for small prompt 

### ISSUE THREAD

**Issue by CodeIter** [bajrangCoder/acode-plugin-chatgpt#10]
I got the error `insufficient_quota` for this small prompt:

Prompt: "test"
```
Status code: 429
Error data: {"error":{"message":"You exceeded your current quota, please check your plan and billing details.","type":"insufficient_quota","param":null,"code":null}}
```

**Comment by bajrangCoder** [comment]
On your openai account you have exceeded your token free tier limit, that's why this error occurred.
For fixing this update your token in plugin or buy premium tier of openai or try hacky way....
