### ISSUE TITLE
Not working at all even in my first time of use

### ISSUE THREAD

**Issue by PhilMinecraft** [bajrangCoder/acode-plugin-chatgpt#17]
It doesn't work at all, here's what it give to me 
![9dERjQC_d](https://github.com/bajrangCoder/acode-plugin-chatgpt/assets/67897800/234afff1-5aa0-4d5e-9115-3a3fb65c5917)

The developer replied and said I used it many times but this was actually my first time of use 🫤
 
![Screenshot_20230615-183942](https://github.com/bajrangCoder/acode-plugin-chatgpt/assets/67897800/b53f2fe6-8030-4258-bec5-fd8fd4ca3aaf)

**Comment by bajrangCoder** [comment]
This is problem with your api key so if you are using it for first time then please check you api key usage on openai website and also check that you have free credit left or it expired.
And also update the plugin to latest version to get latest features.
