### ISSUE TITLE
code 429

### ISSUE THREAD

**Issue by binrusdi** [bajrangCoder/acode-plugin-chatgpt#21]
saya mendapatkan kesalahan seperti ini

`Status code: 429
{"error":{"message":"You exceeded your current quota, please check your plan and billing details.","type":"insufficient_quota","param":null,"code":"insufficient_quota"}}`

**Comment by bajrangCoder** [comment]
It's your api token problem, and please use English because I am not able to get you in your native language

**Comment by hashim-balouch** [comment]
> It's your api token problem, and please use English because I am not able to get you in your native language 

How do we resolve it?

**Comment by bajrangCoder** [comment]
Check your open ai dashboard.
I guess your token is expired, you will need to get new one if available(free)

**Comment by hashim-balouch** [comment]
I have tried two to three times with new api tokens from chat gpt but I
still get the same error.

**Comment by bajrangCoder** [comment]
So please check your token status in openai dashboard

**Comment by hashim-balouch** [comment]
Ok, I will check.
