### ISSUE TITLE
Can you add Gemini version?

### ISSUE THREAD

**Issue by fuji-184** [bajrangCoder/acode-plugin-chatgpt#25]
Hello, pleasee can you add the Gemini version? because the ChatGPT API is not free while the Gemini API is free 😭

**Comment by bajrangCoder** [comment]
Sure! actually I had started development but stopped it because of no interest But I will resume it

**Comment by fuji-184** [comment]
Thank youuu, Im learning how to create a plugin too but still confused about the Acode library 🤧🤧🤧 for the image generator you can use HuggingFace serverless Stable Diffusion 2.1 model API here : 

https://huggingface.co/stabilityai/stable-diffusion-2-1

Or other free model there that can be deployed serverless or other free image generator model that you know

**Comment by bajrangCoder** [comment]
Sure , I will rename this plug-in and add option to select your desired provider such as openai , gemini, llama or any other

**Comment by fuji-184** [comment]
Thank youuu

**Comment by bajrangCoder** [comment]
Gemini is already available
