### ISSUE TITLE
Gemini api nya gmn bikinnya 

### ISSUE THREAD

**Issue by Pri-aRy-OPy** [bajrangCoder/acode-plugin-chatgpt#27]

**Comment by bajrangCoder** [comment]
I think you want gemini integration, if so then it's work in progress..

Keep an eye on https://github.com/bajrangCoder/acode-plugin-chatgpt/tree/alpha

**Comment by Pri-aRy-OPy** [comment]
Kapan di proses

**Comment by bajrangCoder** [comment]
> Kapan di proses

Soon, and also coming with other model providers too like ollama , gemini , etc

**Comment by bajrangCoder** [comment]
Already available
