### ISSUE TITLE
Can't copy my sent queries

### ISSUE THREAD

**Issue by PatAbah** [bajrangCoder/acode-plugin-chatgpt#3]
I notice I can easily select and copy ChatGPT's response, however, that's not the case with queries I send. Long pressing doesn't work.

It would be great to make user's sent query selectable for copy. Sometimes I write a long query, ChatGPT fails to respond, and I then have to retype my entire query instead of just copying and pasting.

**Comment by bajrangCoder** [comment]
Ok, in next update you will get this feature.
Thanks for reporting ❤️
