### ISSUE TITLE
So the api is not free to use?

### ISSUE THREAD

**Issue by RaSan147** [bajrangCoder/acode-plugin-chatgpt#5]
I'm hitting this message .

> Status code: 429
Error data: {"error":{"message":"You exceeded your current quota, please check your plan and billing details.","type":"insufficient_quota","param":null,"code":null}}

Should i buy a subscription on openai?

**Comment by bajrangCoder** [comment]
Yeah, Openai only gives you $18 for free , so utilise it judicially .
If you want you can buy or create a new account on openai website then use it wisely.
